using System;
using System.Collections.Generic;
using System.IO;
using System.Runtime.CompilerServices;
using DiveMap.Core;
using NUnit.Framework;

namespace DiveMap.Tests
{
    /// <summary>
    /// C6 phase 2 — which placed items get a brain, checked against EVERY module in the shipped
    /// manifest rather than against a handful of examples.
    ///
    /// 🔴 This is the test that would have caught the bug the phase exists to fix. The old routing
    /// was two id-prefix checks (<c>school:</c>/<c>pod:</c> and <c>msh:</c>) and it silently sent
    /// 58 species of fish, shark, ray, octopus and turtle down the scenery path, where they were
    /// loaded perfectly and never moved. Nothing failed. Nothing logged. The only way to find out
    /// was to look at a reef and notice that the hammerhead was a statue.
    ///
    /// The other half matters just as much and is easier to get wrong in the other direction: a
    /// coral head, a wreck, a mooring block or a warp gate must NEVER be handed a swimming brain.
    /// </summary>
    public class MarineRoutingTests
    {
        /// <summary>
        /// Every module in StreamingAssets/asset_manifest.json as <c>id|KIND</c> — all 275, not
        /// only the animals, because "does a wreck stay put" is exactly as much a part of the
        /// contract as "does a shark swim". Regenerated by
        /// <see cref="ListMatchesTheShippedManifest"/>.
        /// </summary>
        public static readonly string[] Modules =
        {
            "rock:0|ROCK",
            "rock:1|ROCK",
            "rock:2|ROCK",
            "rock:3|ROCK",
            "coral:0|CORAL",
            "coral:1|CORAL",
            "coral:2|CORAL",
            "coral:3|CORAL",
            "anemone:0|ANEMONE",
            "anemone:1|ANEMONE",
            "anemone:2|ANEMONE",
            "fish:0|FISH",
            "fish:1|FISH",
            "fish:2|FISH",
            "fish:3|FISH",
            "turtle:0|TURTLE",
            "turtle:1|TURTLE",
            "wreck:0|WRECK",
            "wreck:1|WRECK",
            "glb_turtle_loggerhead|TURTLE",
            "cor:amber_tree|CORAL",
            "cor:cerebral_sphere|CORAL",
            "cor:crimson1|CORAL",
            "cor:crimson2|CORAL",
            "cor:crimson_fan|CORAL",
            "cor:crown_tentacles|CORAL",
            "cor:golden_chrysanth|CORAL",
            "cor:golden_sponge|CORAL",
            "cor:golden_tree|CORAL",
            "cor:hairy_mushroom|CORAL",
            "cor:ivory|CORAL",
            "cor:ivory_cluster|CORAL",
            "cor:ivory_tree|CORAL",
            "cor:orange_tree|CORAL",
            "cor:peach_cluster|CORAL",
            "cor:pink_cloud_tree|CORAL",
            "cor:pink_bloom|CORAL",
            "cor:pink_bouquet|CORAL",
            "cor:rosy_tree|CORAL",
            "cor:white_cluster|CORAL",
            "msh:turtle|MARINE_LIFE",
            "msh:barracuda|MARINE_LIFE",
            "msh:lionfish|MARINE_LIFE",
            "msh:crab|MARINE_LIFE",
            "msh:seahorse|MARINE_LIFE",
            "msh:whaleshark|MARINE_LIFE",
            "msh:manta|MARINE_LIFE",
            "msh:trevally|MARINE_LIFE",
            "msh:boxfish|MARINE_LIFE",
            "msh:tiger_shark|MARINE_LIFE",
            "msh:silvertip_shark|MARINE_LIFE",
            "msh:leopard_shark|MARINE_LIFE",
            "msh:nurse_shark|MARINE_LIFE",
            "msh:whitetip_reef_shark|MARINE_LIFE",
            "msh:blacktip_reef_shark|MARINE_LIFE",
            "msh:thresher_shark|MARINE_LIFE",
            "msh:bluefin_tuna|MARINE_LIFE",
            "msh:tuna|MARINE_LIFE",
            "msh:sailfish|MARINE_LIFE",
            "msh:sperm_whale|MARINE_LIFE",
            "msh:beluga_whale|MARINE_LIFE",
            "msh:orca|MARINE_LIFE",
            "msh:dolphin_real|MARINE_LIFE",
            "msh:humpback_whale|MARINE_LIFE",
            "msh:oceanic_manta|MARINE_LIFE",
            "msh:black_manta|MARINE_LIFE",
            "msh:eagle_ray|MARINE_LIFE",
            "msh:mola_mola|MARINE_LIFE",
            "school:barracuda|SCHOOL",
            "school:scad|SCHOOL",
            "pod:humpback|SCHOOL",
            "pod:eagle_ray|SCHOOL",
            "pod:dolphin|SCHOOL",
            "pod:yellowtail|SCHOOL",
            "pod:hammerhead|SCHOOL",
            "pod:blacktip|SCHOOL",
            "school:batfish|SCHOOL",
            "school:parrotfish_prismatic|SCHOOL",
            "pod:orca|SCHOOL",
            "boat:dive|BOAT",
            "boat:motor|BOAT",
            "boat:tender|BOAT",
            "boat:sail|BOAT",
            "boat:cruise|BOAT",
            "boat:yacht|BOAT",
            "boat:raft|BOAT",
            "boat:classic|BOAT",
            "cc0:rock_a|ROCK",
            "cc0:rock_b|ROCK",
            "cc0:rock_cluster|ROCK",
            "cc0:rock_c|ROCK",
            "cc0:rock_d|ROCK",
            "cc0:rock_e|ROCK",
            "cc0:rock_f|ROCK",
            "cc0:rock_large|ROCK",
            "cc0:rock_med|ROCK",
            "cc0:rock_small|ROCK",
            "cc0:rock_boulder|ROCK",
            "cc0:rock_stone2|ROCK",
            "cc0:rock_stone3|ROCK",
            "cc0:rock_pile|ROCK",
            "cc0:rock_group|ROCK",
            "cc0:wreck_ship|WRECK",
            "msh:wreck_ship|WRECK",
            "cc0:wreck_anchor|WRECK",
            "cc0:wreck_airplane|WRECK",
            "cc0:wreck_moto|WRECK",
            "cc0:wreck_car|WRECK",
            "cc0:wreck_barrel|WRECK",
            "cc0:wreck_truck|WRECK",
            "cc0:wreck_tire|WRECK",
            "cc0:wreck_container|WRECK",
            "cc0:wreck_chang|WRECK",
            "cc0:wreck_prab|WRECK",
            "cc0:wreck_hardeep|WRECK",
            "cc0:statue_singha|WRECK",
            "cc0:kraken|SPECIAL",
            "cc0:poseidon|SPECIAL",
            "nat:tree|WRECK",
            "nat:pine|WRECK",
            "nat:palm|WRECK",
            "nat:palms|WRECK",
            "nat:mountain|WRECK",
            "nat:peak|WRECK",
            "nat:kelp|WRECK",
            "nat:seaweed|WRECK",
            "nat:bush|WRECK",
            "nat:grass|WRECK",
            "nat:tallgrass|WRECK",
            "nat:terrain|WRECK",
            "losin:octopus_ringed|MARINE_LIFE",
            "losin:azure_stripe|MARINE_LIFE",
            "losin:pufferfish_bigeye|MARINE_LIFE",
            "losin:banded_fish|MARINE_LIFE",
            "losin:blue_spotted_stingray|MARINE_LIFE",
            "losin:snapper_blushing|MARINE_LIFE",
            "losin:shrimp_acrobat|MARINE_LIFE",
            "losin:shrimp_longhorn|MARINE_LIFE",
            "losin:parrotfish_mosaic|MARINE_LIFE",
            "losin:octopus_crimson|MARINE_LIFE",
            "losin:parrotfish_crimson|MARINE_LIFE",
            "losin:mantis_shrimp|MARINE_LIFE",
            "losin:devil_ray|MARINE_LIFE",
            "losin:pufferfish_golden|MARINE_LIFE",
            "losin:garden_eel|MARINE_LIFE",
            "losin:guitar_shark|MARINE_LIFE",
            "losin:hammerhead_shark|MARINE_LIFE",
            "losin:parrotfish_honeycomb|MARINE_LIFE",
            "losin:indigo_velvet|MARINE_LIFE",
            "losin:kaleidoscope_beetle|MARINE_LIFE",
            "losin:moray_leopard|MARINE_LIFE",
            "losin:leopard_fish|MARINE_LIFE",
            "losin:marble_stingray|MARINE_LIFE",
            "losin:moorish_idol|MARINE_LIFE",
            "losin:sea_serpent|MARINE_LIFE",
            "losin:octopus|MARINE_LIFE",
            "losin:butterflyfish|MARINE_LIFE",
            "losin:parrotfish_prismatic|MARINE_LIFE",
            "losin:prismatic_reef|MARINE_LIFE",
            "losin:reef_manta_ray|MARINE_LIFE",
            "losin:blue_tang|MARINE_LIFE",
            "losin:scorpionfish|MARINE_LIFE",
            "losin:lobster_aurora|MARINE_LIFE",
            "losin:spotted_harbor|MARINE_LIFE",
            "losin:stonefish|MARINE_LIFE",
            "losin:clownfish_three_band|MARINE_LIFE",
            "losin:clownfish_two_band|MARINE_LIFE",
            "losin:bannerfish|MARINE_LIFE",
            "losin:parrotfish_yellowface|MARINE_LIFE",
            "losin:pygmy_seahorse|MARINE_LIFE",
            "mdl:bull_shark|MARINE_LIFE",
            "mdl:great_white_shark|MARINE_LIFE",
            "mdl:whitetip_shark|MARINE_LIFE",
            "mdl:dorado|MARINE_LIFE",
            "mdl:batfish|MARINE_LIFE",
            "mdl:batfish_juvenile|MARINE_LIFE",
            "mdl:coralfish|MARINE_LIFE",
            "mdl:sardine|MARINE_LIFE",
            "mdl:seal|MARINE_LIFE",
            "mdl:penguin|MARINE_LIFE",
            "mdl:penguin_emperor|MARINE_LIFE",
            "mdl:leafy_seadragon|MARINE_LIFE",
            "mdl:giant_clam|MARINE_LIFE",
            "sw:buoy_red|WRECK",
            "sw:buoy_yellow|WRECK",
            "sw:boonsung|SPECIAL",
            "sw:htms732|SPECIAL",
            "sw:kingcruiser|SPECIAL",
            "sw:golden_trident|SPECIAL",
            "sw:stone_king|SPECIAL",
            "ruin:byzantine_arch|SPECIAL",
            "ruin:crystal_arch|SPECIAL",
            "ruin:grand_byzantine|SPECIAL",
            "ruin:domed_temple|SPECIAL",
            "ruin:fantasy_gate|SPECIAL",
            "ruin:stepped_stone|SPECIAL",
            "ruin:ornate_monument|SPECIAL",
            "ruin:broken_pillars|SPECIAL",
            "ruin:long_arch|SPECIAL",
            "ruin:ancient_byzantine|SPECIAL",
            "ruin:ancient_ornate|SPECIAL",
            "stat:verdant_poseidon|SPECIAL",
            "stat:stormbringer|SPECIAL",
            "stat:ascendant_warrior|SPECIAL",
            "losin:lighthouse|WRECK",
            "art:covered_stone|ARTIFICIAL",
            "art:lichen_cylinder|ARTIFICIAL",
            "art:monolith|ARTIFICIAL",
            "art:1268|ARTIFICIAL",
            "art:1272|ARTIFICIAL",
            "art:1273|ARTIFICIAL",
            "art:1274|ARTIFICIAL",
            "art:1275|ARTIFICIAL",
            "art:1276|ARTIFICIAL",
            "art:1277|ARTIFICIAL",
            "art:1278|ARTIFICIAL",
            "art:1279|ARTIFICIAL",
            "art:1280|ARTIFICIAL",
            "art:1281|ARTIFICIAL",
            "art:1282|ARTIFICIAL",
            "art:1283|ARTIFICIAL",
            "art:1284|ARTIFICIAL",
            "art:1285|ARTIFICIAL",
            "art:1286|ARTIFICIAL",
            "art:1287|ARTIFICIAL",
            "art:1288|ARTIFICIAL",
            "art:1289|ARTIFICIAL",
            "art:1290|ARTIFICIAL",
            "art:1291|ARTIFICIAL",
            "art:1292|ARTIFICIAL",
            "art:1293|ARTIFICIAL",
            "art:1294|ARTIFICIAL",
            "art:1295|ARTIFICIAL",
            "art:1296|ARTIFICIAL",
            "art:1297|ARTIFICIAL",
            "art:1298|ARTIFICIAL",
            "art:1299|ARTIFICIAL",
            "art:1300|ARTIFICIAL",
            "art:1301|ARTIFICIAL",
            "art:1302|ARTIFICIAL",
            "art:1303|ARTIFICIAL",
            "art:1304|ARTIFICIAL",
            "art:1305|ARTIFICIAL",
            "art:1306|ARTIFICIAL",
            "art:1307|ARTIFICIAL",
            "art:1308|ARTIFICIAL",
            "art:1309|ARTIFICIAL",
            "art:1310|ARTIFICIAL",
            "art:1311|ARTIFICIAL",
            "art:1312|ARTIFICIAL",
            "art:1313|ARTIFICIAL",
            "art:1314|ARTIFICIAL",
            "art:1315|ARTIFICIAL",
            "art:1316|ARTIFICIAL",
            "art:1317|ARTIFICIAL",
            "art:1318|ARTIFICIAL",
            "art:1319|ARTIFICIAL",
            "art:1320|ARTIFICIAL",
            "art:1321|ARTIFICIAL",
            "art:1322|ARTIFICIAL",
            "art:1323|ARTIFICIAL",
            "art:1324|ARTIFICIAL",
            "art:1325|ARTIFICIAL",
            "art:1326|ARTIFICIAL",
            "art:1327|ARTIFICIAL",
            "art:1328|ARTIFICIAL",
            "art:1330|ARTIFICIAL",
            "art:1331|ARTIFICIAL",
            "art:1332|ARTIFICIAL",
            "art:1333|ARTIFICIAL",
            "art:1334|ARTIFICIAL",
            "art:1336|ARTIFICIAL",
            "art:1337|ARTIFICIAL",
            "art:1338|ARTIFICIAL",
            "art:1339|ARTIFICIAL",
        };

        private static void Split(string row, out string id, out string kind)
        {
            int bar = row.IndexOf('|');
            id = row.Substring(0, bar);
            kind = row.Substring(bar + 1);
        }

        // ── exhaustive over the manifest ─────────────────────────────────────────

        [Test]
        public void EveryModuleRoutesToExactlyTheRightSystem()
        {
            var wrong = new List<string>();
            foreach (string row in Modules)
            {
                Split(row, out string id, out string kind);

                bool isSchoolId = id.StartsWith("school:", StringComparison.OrdinalIgnoreCase)
                               || id.StartsWith("pod:", StringComparison.OrdinalIgnoreCase);
                bool isAnimal = kind == "MARINE_LIFE" || kind == "SCHOOL"
                             || kind == "FISH" || kind == "TURTLE";

                MarineRoute want = isSchoolId ? MarineRoute.School
                                 : !isAnimal  ? MarineRoute.None
                                 : kind == "SCHOOL" ? MarineRoute.School
                                 : MarineRoute.Solo;

                MarineRoute got = MarineRouting.For(id, kind);
                if (got != want) wrong.Add($"{id} ({kind}): want {want}, got {got}");
            }
            Assert.IsEmpty(wrong, string.Join("\n", wrong));
        }

        [Test]
        public void TheCountsAreWhatTheReefShouldContain()
        {
            int solo = 0, school = 0, none = 0;
            foreach (string row in Modules)
            {
                Split(row, out string id, out string kind);
                switch (MarineRouting.For(id, kind))
                {
                    case MarineRoute.Solo:   solo++;   break;
                    case MarineRoute.School: school++; break;
                    default:                 none++;   break;
                }
            }
            // 🔴 88 is the number this whole phase is about. Before it, THIRTY of those were
            // driven (the msh:* heroes) and the other fifty-eight were furniture.
            Assert.AreEqual(88, solo, "solo animals");
            Assert.AreEqual(11, school, "shoals and pods");
            Assert.AreEqual(176, none, "scenery — coral, rock, wreck, boat, artificial, special");
            Assert.AreEqual(275, Modules.Length);
        }

        [Test]
        public void NoSceneryEverGetsABrain()
        {
            foreach (string row in Modules)
            {
                Split(row, out string id, out string kind);
                if (kind == "MARINE_LIFE" || kind == "SCHOOL" || kind == "FISH" || kind == "TURTLE")
                    continue;
                Assert.AreEqual(MarineRoute.None, MarineRouting.For(id, kind),
                                $"{id} is {kind} and must stay furniture");
                Assert.IsFalse(MarineRouting.IsSolo(id, kind), id);
            }
        }

        [Test]
        public void EveryAnimalGetsOneOrTheOther()
        {
            foreach (string id in SpeciesCoverageTests.Animals)
            {
                // Kind is not needed for the shoals (the prefix decides), and for the rest the
                // coverage list is animals-only by construction — so anything that comes back
                // None here is an animal that would be loaded as scenery.
                string kind = MarineRouting.IsSchoolId(id) ? "SCHOOL" : "MARINE_LIFE";
                Assert.AreNotEqual(MarineRoute.None, MarineRouting.For(id, kind), id);
            }
        }

        // ── the specific species that were furniture ─────────────────────────────

        [Test]
        public void TheFiftyEightThatWereFurnitureNowSwim()
        {
            foreach (string id in new[]
            {
                "losin:hammerhead_shark", "losin:moray_leopard", "losin:octopus",
                "losin:reef_manta_ray", "losin:blue_tang", "losin:clownfish_two_band",
                "mdl:great_white_shark", "mdl:sardine", "mdl:penguin", "mdl:seal",
                "mdl:leafy_seadragon", "glb_turtle_loggerhead", "fish:0", "turtle:1",
            })
                Assert.IsTrue(MarineRouting.IsSolo(id, "MARINE_LIFE"), id);
        }

        [Test]
        public void ShoalsStayShoals()
        {
            // A pod of orcas is SCHOOL-kind AND an animal; the prefix has to win, or the map
            // grows eleven separate orca brains instead of one pod.
            foreach (string id in new[] { "school:scad", "school:barracuda", "pod:orca",
                                          "pod:humpback", "pod:hammerhead" })
            {
                Assert.AreEqual(MarineRoute.School, MarineRouting.For(id, "SCHOOL"), id);
                Assert.IsFalse(MarineRouting.IsSolo(id, "SCHOOL"), id);
            }
        }

        [Test]
        public void WarpGatesAreNeverAnimals()
        {
            // A gate is built from primitives and is in no manifest, so it can arrive with any
            // kind at all — including, if a caller is careless, an animal's.
            Assert.AreEqual(MarineRoute.None, MarineRouting.For("warp:0", "MARINE_LIFE"));
            Assert.AreEqual(MarineRoute.None, MarineRouting.For("warp:1", null));
        }

        [Test]
        public void UnknownKindsAndNullsAreInert()
        {
            Assert.AreEqual(MarineRoute.None, MarineRouting.For("losin:octopus", null));
            Assert.AreEqual(MarineRoute.None, MarineRouting.For("losin:octopus", "GRAVEL"));
            Assert.AreEqual(MarineRoute.None, MarineRouting.For(null, null));
            Assert.AreEqual(MarineRoute.None, MarineRouting.For("", ""));
            Assert.IsFalse(MarineRouting.IsAnimalKind(null));
        }

        [Test]
        public void KindMatchingIsCaseInsensitive()
        {
            Assert.AreEqual(MarineRoute.Solo, MarineRouting.For("losin:octopus", "marine_life"));
            Assert.AreEqual(MarineRoute.School, MarineRouting.For("POD:ORCA", "school"));
        }

        // ── the hunt budget ──────────────────────────────────────────────────────

        [Test]
        public void TheHuntBudgetCutsOffWhereItSays()
        {
            Assert.IsTrue(MarineRouting.MayHunt(0));
            Assert.IsTrue(MarineRouting.MayHunt(MarineRouting.SoloHuntBudget - 1));
            Assert.IsFalse(MarineRouting.MayHunt(MarineRouting.SoloHuntBudget));
            Assert.IsFalse(MarineRouting.MayHunt(500));
            Assert.IsFalse(MarineRouting.MayHunt(-1));
            // The scan is O(n²) per tick: 40² = 1,600 tests every 0.7 s is free, and the next
            // order of magnitude is not. If this number grows, re-measure on a phone first.
            Assert.LessOrEqual(MarineRouting.SoloHuntBudget, 64);
        }

        // ── per-placement seeding ────────────────────────────────────────────────

        [Test]
        public void FiveSharksOnOneMapAreFiveDifferentSharks()
        {
            // 🔴 The Posidon case: an author drops the same shark five times. Seeded from a
            // counter they would be identical; seeded from the clock they would be different
            // every time the map was opened and no screenshot would ever reproduce.
            var seen = new HashSet<uint>();
            for (int i = 0; i < 5; i++)
                seen.Add(MarineRouting.PlacementSeed("losin:hammerhead_shark", i * 37.5, 60.0, i * -21.25));
            Assert.AreEqual(5, seen.Count);
        }

        [Test]
        public void TheSameMapReopensTheSame()
        {
            Assert.AreEqual(MarineRouting.PlacementSeed("mdl:seal", 12.3, 40.0, -8.75),
                            MarineRouting.PlacementSeed("mdl:seal", 12.3, 40.0, -8.75));
            // Quantised to a tenth of a unit, so the sub-millimetre wobble a float round-trip
            // through the save file introduces cannot reseed an animal nobody moved.
            //
            // ⚠️ A quantisation has boundaries and this one is no exception: a coordinate sitting
            // exactly on a .x5 can still flip (−8.75 rounds to −88, −8.7499 to −87). That is
            // acceptable — it takes an author placing an animal on precisely that line AND the
            // file round-tripping across it, and the cost is one animal drawing a different
            // personality. The alternative, no quantisation at all, means EVERY animal rerolls on
            // every save.
            Assert.AreEqual(MarineRouting.PlacementSeed("mdl:seal", 12.30, 40.0, -8.72),
                            MarineRouting.PlacementSeed("mdl:seal", 12.3001, 40.0, -8.7201));
        }

        [Test]
        public void DifferentSpeciesInTheSameSpotDiffer()
        {
            Assert.AreNotEqual(MarineRouting.PlacementSeed("mdl:seal", 5.0, 5.0, 5.0),
                               MarineRouting.PlacementSeed("mdl:penguin", 5.0, 5.0, 5.0));
        }

        [Test]
        public void ASeedIsNeverZero()
        {
            // 0 is a legitimate hash output and a terrible seed: FishMind.Rand01 folds it with
            // the tick, and a whole species sharing seed 0 would share every decision.
            Assert.AreNotEqual(0u, MarineRouting.PlacementSeed("", 0, 0, 0));
            Assert.AreNotEqual(0u, MarineRouting.PlacementSeed(null, 0, 0, 0));
        }

        // ── the list itself ──────────────────────────────────────────────────────

        [Test]
        public void ListMatchesTheShippedManifest()
        {
            string path = ManifestPath();
            if (path == null || !File.Exists(path))
                Assert.Ignore("asset_manifest.json not reachable from here (player build).");

            var fromFile = new List<string>();
            string pending = null;
            foreach (string line in File.ReadAllLines(path))
            {
                string id = Between(line, "\"id\": \"", "\"");
                if (id != null) { pending = id; continue; }
                string kind = Between(line, "\"kind\": \"", "\"");
                if (kind == null) continue;
                if (pending != null) fromFile.Add(pending + "|" + kind);
                pending = null;
            }

            Assert.Greater(fromFile.Count, 0, "could not parse " + path);
            CollectionAssert.AreEquivalent(Modules, fromFile,
                "the manifest changed — regenerate MarineRoutingTests.Modules");
        }

        private static string ManifestPath([CallerFilePath] string here = "")
        {
            DirectoryInfo d = new FileInfo(here).Directory;          // EditMode
            for (int i = 0; i < 3 && d != null; i++) d = d.Parent;   // Tests → Assets → DiveMap
            return d == null ? null : Path.Combine(d.FullName, "Assets", "StreamingAssets", "asset_manifest.json");
        }

        private static string Between(string s, string a, string b)
        {
            int i = s.IndexOf(a, StringComparison.Ordinal);
            if (i < 0) return null;
            i += a.Length;
            int j = s.IndexOf(b, i, StringComparison.Ordinal);
            return j < 0 ? null : s.Substring(i, j - i);
        }
    }
}
