// The HERO variant of the body wave. Same motion as DiveMap/FishWave — literally the same code,
// via DM_FishWave.cginc — but it keeps the model's normal and emissive maps.
//
// Why two shaders instead of one with a keyword. A surface shader that assigns o.Normal anywhere
// in its surf function is regenerated by Unity with a full tangent-space basis (three float4
// interpolators in place of one float3 world normal) in EVERY variant, because that decision is
// made from the source text, not per keyword. DiveMap/FishWave draws 1,100 instances a frame and
// must not pay for a normal map it never samples. A whale shark is one object that fills the
// screen and can afford it. The wave itself lives in the .cginc precisely so splitting the
// SHADING like this cannot make the two animate differently.
//
// Both maps default to no-ops ("bump" = flat, "black" = unlit), so a GLB that ships neither
// renders exactly as it does under DM_Standard, plus the bend.
Shader "DiveMap/FishWaveDetail"
{
    Properties
    {
        _Color      ("Colour", Color) = (1,1,1,1)
        _MainTex    ("Albedo", 2D) = "white" {}
        _Glossiness ("Smoothness", Range(0,1)) = 0.1
        _Metallic   ("Metallic", Range(0,1)) = 0.0
        [Normal] _BumpMap ("Normal map", 2D) = "bump" {}
        _EmissionMap   ("Emission map", 2D) = "black" {}
        _EmissionColor ("Emission colour", Color) = (0,0,0,1)
        [Enum(UnityEngine.Rendering.CullMode)] _Cull ("Cull", Float) = 2

        // ── identical to DiveMap/FishWave; see DM_FishWave.cginc for what each one does ──
        _WaveLen    ("Body length (model units)", Float) = 1.9
        _WaveSpan   ("Half wingspan (model units)", Float) = 0.95
        _WaveAmp    ("Tip amplitude (× length)", Range(0,0.5)) = 0.10
        _WaveCycles ("Waves along body", Range(0.2,3)) = 0.95
        _WaveAnchor ("Head anchored", Range(0,1)) = 1.0
        _WaveRecoil ("Head recoil", Range(0,0.4)) = 0.10
        _WaveGust   ("Amplitude drift", Range(0,0.6)) = 0.28
        _WaveEffort ("Effort", Range(0,3)) = 1.0
        _WavePhase  ("Beat phase (rad)", Float) = 0.0
        _WaveMode   ("Gait (0 body, 1 wing)", Float) = 0
        _WaveFwd    ("Nose axis (object space)", Vector) = (0,0,1,0)
        _WaveSide   ("Lateral axis (object space)", Vector) = (1,0,0,0)
        _WaveDir    ("Thrust axis (object space)", Vector) = (1,0,0,0)
    }

    SubShader
    {
        Tags { "RenderType" = "Opaque" }
        LOD 200
        Cull [_Cull]

        CGPROGRAM
        #pragma surface surf Standard vertex:vert addshadow fullforwardshadows
        #pragma multi_compile_instancing
        #pragma target 3.0

        #include "DM_FishWave.cginc"

        sampler2D _MainTex;
        sampler2D _BumpMap;
        sampler2D _EmissionMap;

        // One UV set on purpose: glTF authors every map on TEXCOORD0, so asking the surface
        // compiler for uv_BumpMap as well would interpolate the same coordinates twice.
        struct Input { float2 uv_MainTex; };

        half   _Glossiness, _Metallic;
        fixed4 _Color, _EmissionColor;

        void vert(inout appdata_full v)
        {
            // The tangent is NOT re-derived from the bend. The wave turns the normal (DM_TipNormal)
            // so the lighting follows the body, and the remaining tangent skew is a fraction of a
            // degree at these amplitudes — far below what a normal map's own detail hides.
            DM_FishBend(v.vertex, v.normal);
        }

        void surf(Input IN, inout SurfaceOutputStandard o)
        {
            fixed4 c = tex2D(_MainTex, IN.uv_MainTex) * _Color;
            o.Albedo     = c.rgb;
            o.Normal     = DM_UnpackNormalRGB(tex2D(_BumpMap, IN.uv_MainTex));
            o.Emission   = tex2D(_EmissionMap, IN.uv_MainTex).rgb * _EmissionColor.rgb;
            o.Metallic   = _Metallic;
            o.Smoothness = _Glossiness;
            o.Alpha      = c.a;
        }
        ENDCG
    }

    // Stripped from a build ⇒ the animal draws unbent, never magenta.
    FallBack "Standard"
}
