name: Acquire activation file
on: workflow_dispatch

jobs:
  activation:
    name: Request .alf
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 6000.0.79f1
      - name: Upload .alf
        uses: actions/upload-artifact@v4
        with:
          name: alf
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
          retention-days: 3
